# Generated by Django 2.2.5 on 2019-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
