# Generated by Django 2.2.5 on 2019-12-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibase', '0002_auto_20191202_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cosmetics',
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='ingredients',
            field=models.ManyToManyField(to='apibase.Ingredient'),
        ),
    ]
